### ISSUE TITLE
Nel bookings array degli schedule, lo user è null

### ISSUE THREAD

**Issue by federico-galfione** [giacomodeliberali/ethos#4]
Quando chiamo get schedules, con delle prenotazioni già effettuate la proprietà user è settata a null per ogni prenotazione

**Comment by giacomodeliberali** [comment]
La proprietà `User` è null quando fai la chiamata e non sei admin, altrimenti gli altri utenti potrebbero vedere gli iscritti ai corsi. Per vedere la lista degli iscritti devi essere admin

**Comment by federico-galfione** [comment]
Il problema è che non so se io mi sono prenotato in questo modo

**Comment by giacomodeliberali** [comment]
Ora la proprietà `user` è valorizzata anche se contiene lo stesso utente di quello che effettua la chiamata. Negli altri utenti è ancora `null`. Ti torna?
